# Generated by Django 2.0.2 on 2019-04-22 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='requesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('sendBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sendBy', to=settings.AUTH_USER_MODEL)),
                ('sendTo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sendTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
