# Generated by Django 2.0.2 on 2019-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting',
            name='requestSent',
            field=models.BooleanField(default=False),
        ),
    ]
